# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Azure subscription 1(573b0f29-d7bf-4edd-8818-e18bcd10c588)'
    ScriptType: 'InlineScript'
    Inline: |
      $rgName = 'PowershellTestdevops
      
      $resourceGroup = Get-AzResourceGroup -Name $rgName -ErrorAction SilentlyContinue
      
      if($resourceGroup -eq $null -or $resourceGroup -eq '')
      {
          New-AzResourceGroup -Name $rgName -Location EastUs -DefaultProfile $defaultContext 
      }
      
      New-AzStorageAccount -ResourceGroupName $rgName -Name testdemodevops123 -SkuName Standard_LRS -Location EastUs -Kind StorageV2 -AccessTier Hot